<?php

/**
 * Implements hook_permission
 */
function click_stats_permission() {
	return array(
		'access own click stats' => array(
			'title' => t('Access own click stats'),
			'description' => t('Allows users to view clicks stats on their own content'),
  		),
 	);
}

/**
 * Implements hook_menu
 */
function click_stats_menu(){
  $items = array();

	// Test items
	$items['click_stats'] = array(
   	  'title' => 'Kliks',
   	  'description' => 'Vacature klik overzicht',
	  'type' => MENU_NORMAL_ITEM,
	  'page callback' => 'click_stats_test_pager',
	  'access arguments' => array('access own click stats')
	); 	 
	
	// needed for jQuery / ajax callback
	$items['click_stats/callback'] = array(
	  'title' => 'Test Pager Callback',
	  'type' => MENU_CALLBACK,
	  'page callback' => '_click_stats_test_pager_callback',
	  'access arguments' => array('access own click stats'),
	);

	return $items;
}

function click_stats_enable() {
	//Make user goto the test pager page.
	$link = l('Test Pager', 'click_stats');
	drupal_set_message("Please visit $link to see Ajaxed paging in action.");
}

function click_stats_test_pager () {

	drupal_add_js(drupal_get_path('module', 'click_stats') . '/jquery.url.js');
	drupal_add_js(drupal_get_path('module', 'click_stats') . '/click_stats.js');
	drupal_add_js('initializeTable();', 'inline');
			
	return ('<div id="table-container"></div>');
}

function _click_stats_test_pager_callback () {
	global $user;
	
	header("Content-type: text/html");
	header("Expires: Wed, 29 Jan 1975 04:15:00 GMT");
	header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
	header("Cache-Control: no-cache, must-revalidate");
	header("Pragma: no-cache");
	
	//Create a list of headers for your Html table (see Drupal 7 docs for theme_table here: http://api.drupal.org/api/drupal/includes--theme.inc/function/theme_table/7
	
	
	$header = array(
		array('data' => 'Titel', 'field' => 'title', 'sort' => 'asc'),
		array('data' => 'Kliks', 'field' => 'clicks'),
	//	array('data' => 'Type', 'field' => 'type'),
		array('data' => 'Aangemaakt op', 'field' => 'created'),
		array('data' => 'gepubliceerd', 'field' => 'status'),
		array('data' => 'Prijs'),
	);

	//Create the Sql query. This uses various parts of Drupal 7's new DBTNG database abstraction layer. See these links for details:
	//Dynamic queries: http://drupal.org/node/310075
	//Extenders: http://drupal.org/node/508796
	//Table sort: http://drupal.org/node/310075#table_sort
	//dsm($user->uid);
	$query = db_select('node', 'n');
	$query->join('pop_links_stats', 'p', 'n.nid = p.nid');
	$query->join('field_data_field_click_price', 'c', 'n.vid = c.revision_id');
	$query->fields('n', array('nid','title','created','status'));
	$query->fields('p', array('url'));
	$query->fields('c', array('field_click_price_value'));
	$query->condition('type', 'vacature');
	if($user->uid !== "1" ) { // build in user is webmaster / admin
		$query->condition('n.uid', $user->uid);	
	}
	$query->groupBy('p.nid');
	$query->addExpression('COUNT(p.nid)', 'clicks');
	$query = $query->extend('PagerDefault')->limit(25);
	$query = $query->extend('TableSort')->orderByHeader($header);
	
	/*
	->condition('status', 1)	//Only published nodes, change condition as it suits you
	->extend('PagerDefault') 	//Pager Extender
		->limit(10)				//10 results per page
	->extend('TableSort')		//Sorting Extender
		->orderByHeader($header)//Field to sort on is picked from $header
	->fields ('n', array ( 
		'nid',
		'title',
		//'type',
		'created',
		'status',
	));
	 * 
	 */
	
	$results = $query
				->execute();

	$rows = array();
	$totalnrclicks = 0;
	$totalprice = 0;
	foreach ($results as $node) {
		$nodeobj = node_load($node->nid);
		
		$totalnodeclickprice = ( $node->clicks * $node->field_click_price_value);
		$rows[] = array(
					'data' => array(
						  l($node->title, $node->url),
						  $node->clicks,
				//		  $node->type,
						  format_date($node->created),
						  ($node->status == 1?t('Ja'):t('Nee')),
						  number_format($totalnodeclickprice,2), // TODO node prijs nog ophalen in query
					),
		);
		$totalnrclicks += $node->clicks;
		$totalprice += $totalnodeclickprice;
	}
	// footer with totals TODO gevens invullen hieronder
	$rows[] = array(
				'data' => array(
					t('Totaal aantal kliks'),
					$totalnrclicks,
					' ',
					' ',
					number_format($totalprice,2),	
				),
	);
	
	//Theme the html table: http://api.drupal.org/api/drupal/includes--theme.inc/function/theme_table/7
	$html = theme('table', 
				array(
					'header' => $header,
					'rows'=>$rows,
					//'caption' => 'Klik overzicht',	//Optional Caption for the table
					'sticky' => TRUE,						//Optional to indicate whether the table headers should be sticky
					'empty' => 'Er is niet geklikt',		//Optional empty text for the table if resultset is empty
				)
			);
	
	//Append pager: http://api.drupal.org/api/drupal/includes--pager.inc/function/theme_pager
	$html .= theme('pager',
				array(
					'tags' => array()
				)
			);
			
	die ($html);
}
